# Importing required Libraries and modules

In [1]:
from sklearn.feature_extraction.text import CountVectorizer 
from nltk.corpus import stopwords
import pandas as pd

In [2]:
import string
from collections import Counter
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import nltk
import warnings
warnings.filterwarnings('ignore')

#  Document A

In [3]:
textA= open('DocA.txt').read()

In [4]:
lower_case = textA.lower()
# str.maketrans removes any punctuations 
cleaned_text = lower_case.translate(str.maketrans('', '', string.punctuation))

# Using word_tokenize to tokenize sentence into words
tokenized_wordsA = word_tokenize(cleaned_text, "english")

# BOW of DocA using countVectorizer

In [5]:
# This step will convert text into tokens 
vect1 = CountVectorizer()

vect1.fit_transform(tokenized_wordsA)
print("bag of words :",vect1.get_feature_names())

bag of words : ['100', '19655', '1988', '1989', '1990s', '1994', '1995', '1999', '2000s', '2010', '201013', '2010s', '2011', '2012', '2014', '2015', '2016', '2017', '2018', '27', '335', '377', '71', '82nd', 'aapke', 'abdul', 'according', 'achieved', 'acting', 'acting6', 'action', 'actor', 'actors', 'addition', 'after', 'aisi', 'also', 'amitabh', 'an', 'and', 'appeal', 'appeal15161718', 'april', 'arjun', 'as', 'aside', 'awards', 'bachchan', 'bail', 'began', 'being', 'bigg', 'biwi', 'blackbuck', 'bollywood', 'boss', 'both', 'brief', 'but', 'by', 'car', 'career', 'case', 'causes', 'celebrity', 'charity', 'cinema78', 'cited', 'comedy', 'commercially', 'continued', 'controversy', 'convicted', 'conviction', 'culpable', 'currently', 'dabangg', 'december', 'decline', 'drama', 'driving', 'earnings', 'ek', 'eldest', 'entertainers', 'family', 'film', 'filmfare', 'films', 'five', 'followed', 'for', 'forbes', 'foundation14', 'greater', 'hai', 'hain', 'has', 'he', 'heard21', 'help', 'highest', 'him'

In [6]:
vect1.vocabulary_

{'abdul': 25,
 'rashid': 165,
 'salim': 173,
 'salman': 174,
 'khan': 119,
 'pronounced': 159,
 'slman': 182,
 'xan': 207,
 'hindi': 103,
 'pronunciation': 160,
 'help': 100,
 'info': 116,
 '27': 19,
 'december': 77,
 '19655': 1,
 'is': 117,
 'an': 38,
 'indian': 115,
 'film': 86,
 'actor': 31,
 'producer': 156,
 'occasional': 143,
 'singer': 181,
 'and': 39,
 'television': 189,
 'personality': 152,
 'in': 112,
 'career': 61,
 'spanning': 184,
 'over': 149,
 'thirty': 193,
 'years': 208,
 'has': 97,
 'received': 168,
 'numerous': 142,
 'awards': 46,
 'including': 114,
 'two': 201,
 'national': 138,
 'as': 44,
 'filmfare': 87,
 'for': 91,
 'acting6': 29,
 'he': 98,
 'cited': 67,
 'the': 191,
 'media': 134,
 'one': 147,
 'of': 144,
 'most': 137,
 'commercially': 69,
 'successful': 186,
 'actors': 32,
 'both': 56,
 'world': 206,
 'cinema78': 66,
 'forbes': 92,
 'included': 113,
 'him': 102,
 'their': 192,
 '2015': 15,
 'list': 131,
 'toppaid': 199,
 '100': 0,
 'celebrity': 64,
 'entertain

# Document B

In [7]:
textB= open('DocB.txt').read()

In [8]:
lower_case = textB.lower()
# str.maketrans removes any punctuations 
cleaned_textB = lower_case.translate(str.maketrans('', '', string.punctuation))

# Using word_tokenize to tokenize sentence into words
tokenized_wordsB = word_tokenize(cleaned_textB, "english")

# BOW of DocB using CountVectorizer

In [12]:
# This step will convert text into tokens 
vect2 = CountVectorizer()

vect2.fit_transform(tokenized_wordsB)
print("bag of words :",vect2.get_feature_names())

bag of words : ['14', '1965', '1980s', '1992', '1993', '1994', '1995', '1997', '1998', '1999', '2000', '2001', '2002', '2004', '2007', '2010', '2013', '2014', '2015', '2017', '80', 'acclaim', 'accolades', 'actor', 'after', 'alcoholic', 'also', 'an', 'and', 'anjaam', 'appearances', 'appeared', 'arts', 'arx', 'as', 'asia', 'asperger', 'audience', 'awarded', 'awards', 'baadshah', 'baazigar', 'been', 'began', 'bollywood', 'born', 'by', 'career', 'chak', 'chennai', 'coach', 'comedies', 'communities', 'connections', 'crime', 'critical', 'darr', 'de', 'debut', 'deewana', 'des', 'described', 'devdas', 'diaspora', 'differences', 'dil', 'dilwale', 'display', 'dulhania', 'early', 'earn', 'earned', 'et', 'express', 'film', 'filmfare', 'films', 'following', 'for', 'france', 'gender', 'gham', 'government', 'grievances', 'hai', 'happy', 'has', 'he', 'highestgrossing', 'him', 'his', 'hockey', 'honour', 'hota', 'identity', 'in', 'include', 'including', 'income', 'india', 'indian', 'initialism', 'is', '

In [13]:
vect2.vocabulary_

{'shah': 155,
 'rukh': 151,
 'khan': 106,
 'pronounced': 141,
 'arx': 33,
 'xan': 179,
 'born': 45,
 'november': 127,
 '1965': 1,
 'also': 26,
 'known': 109,
 'by': 46,
 'the': 169,
 'initialism': 101,
 'srk': 160,
 'is': 102,
 'an': 27,
 'indian': 100,
 'actor': 23,
 'film': 74,
 'producer': 139,
 'and': 28,
 'television': 166,
 'personality': 136,
 'referred': 146,
 'to': 172,
 'in': 95,
 'media': 118,
 'as': 34,
 'baadshah': 40,
 'of': 129,
 'bollywood': 44,
 'reference': 145,
 'his': 90,
 '1999': 9,
 'king': 108,
 'he': 87,
 'has': 86,
 'appeared': 31,
 'more': 120,
 'than': 168,
 '80': 20,
 'films': 76,
 'earned': 71,
 'numerous': 128,
 'accolades': 22,
 'including': 97,
 '14': 0,
 'filmfare': 75,
 'awards': 39,
 'government': 82,
 'india': 99,
 'awarded': 38,
 'him': 89,
 'padma': 134,
 'shri': 156,
 'france': 79,
 'ordre': 133,
 'des': 60,
 'arts': 32,
 'et': 72,
 'lettres': 114,
 'legion': 113,
 'honour': 92,
 'significant': 157,
 'following': 77,
 'asia': 35,
 'diaspora': 63,


In [25]:
#Fit and transform and predict if the word is present or not
#This is widely used for document or subject classification

In [11]:
c_vect = CountVectorizer()
c_vect.fit(tokenized_wordsA)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [15]:
c_new_vect = c_vect.transform(tokenized_wordsB)

print ("array \n ",c_new_vect.toarray())

# Compare with the indexes
print ("features names \n", vect1.get_feature_names() )

array 
  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
features names 
 ['100', '19655', '1988', '1989', '1990s', '1994', '1995', '1999', '2000s', '2010', '201013', '2010s', '2011', '2012', '2014', '2015', '2016', '2017', '2018', '27', '335', '377', '71', '82nd', 'aapke', 'abdul', 'according', 'achieved', 'acting', 'acting6', 'action', 'actor', 'actors', 'addition', 'after', 'aisi', 'also', 'amitabh', 'an', 'and', 'appeal', 'appeal15161718', 'april', 'arjun', 'as', 'aside', 'awards', 'bachchan', 'bail', 'began', 'being', 'bigg', 'biwi', 'blackbuck', 'bollywood', 'boss', 'both', 'brief', 'but', 'by', 'car', 'career', 'case', 'causes', 'celebrity', 'charity', 'cinema78', 'cited', 'comedy', 'commercially', 'continued', 'controversy', 'convicted', 'conviction', 'culpable', 'currently', 'dabangg', 'december', 'decline', 'drama', 'driving', 'earnings', 'ek', 'eldest', 'entertainers', 'family', 'film', 'filmfare', 'film

# Using TfidVectorizer for words present of DocB to DocA

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

import pandas as pd

tfid = TfidfVectorizer(smooth_idf=False)

In [23]:
# And now testing TFIDF vectorizer:
# You can still specify n-grams here.

vectorizer = TfidfVectorizer(ngram_range=(2, 2))
X = vectorizer.fit_transform(tokenized_wordsA)


# Testing the TFIDF value + ngrams:
print(X.toarray())

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [24]:
# Testing TFIDF vectorizer without normalization:
# You can still specify n-grams here.

vectorizer = TfidfVectorizer(ngram_range=(2, 2), norm=None)

X = vectorizer.fit_transform(tokenized_wordsA)

# Testing TFIDF value before normalization:
print(X.toarray())

[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [6.18178355]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.  